CREATE TABLE TBL_TESTE(
	TST_ID INTEGER,
	TST_NOME VARCHAR(50),
	TST_NASCIMENTO DATE
);

INSERT INTO TBL_TESTE (TST_ID, TST_NOME, TST_NASCIMENTO) VALUES (
	1,
	'alessandro',
	'2000-05-31'
);

INSERT INTO TBL_TESTE (TST_ID, TST_NOME, TST_NASCIMENTO) VALUES (
	2,
	'ivana',
	'1985-04-12'
);

INSERT INTO TBL_TESTE (TST_ID, TST_NOME, TST_NASCIMENTO) VALUES (
	3,
	'antonio',
	'1999-02-21'
);

INSERT INTO TBL_TESTE (TST_ID, TST_NOME, TST_NASCIMENTO) VALUES (
	4,
	'livia',
	'2001-10-02'
);

INSERT INTO TBL_TESTE (TST_ID, TST_NOME, TST_NASCIMENTO) VALUES (
	5,
	'edivaldo',
	'1956-05-31'
);

INSERT INTO TBL_TESTE (TST_ID, TST_NOME, TST_NASCIMENTO) VALUES (
	6,
	'mariana',
	'1966-12-01'
);
