SELECT TST_NOME,
CASE
	WHEN
	EXTRACT (DAY FROM CURRENT_DATE) - EXTRACT(DAY FROM TBL_TESTE.TST_NASCIMENTO) <= 0
	AND
	EXTRACT (MONTH FROM CURRENT_DATE) - EXTRACT(MONTH FROM TBL_TESTE.TST_NASCIMENTO) <= 0
	THEN
	EXTRACT (YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM TBL_TESTE.TST_NASCIMENTO) - 1 || ' anos.'
	
	WHEN
	EXTRACT(MONTH FROM TBL_TESTE.TST_NASCIMENTO) = 2
	AND
	EXTRACT(DAY FROM TBL_TESTE.TST_NASCIMENTO) >= 29
	AND
	MOD(EXTRACT(YEAR FROM TBL_TESTE.TST_NASCIMENTO), 4) != 0
	THEN
	EXTRACT (DAY FROM CURRENT_DATE) - EXTRACT(DAY FROM TBL_TESTE.TST_NASCIMENTO) || ' dias ' ||
	EXTRACT (MONTH FROM CURRENT_DATE) - EXTRACT(MONTH FROM TBL_TESTE.TST_NASCIMENTO) + 1 || ' meses ' ||
	EXTRACT (YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM TBL_TESTE.TST_NASCIMENTO) || ' anos.'

	WHEN
	EXTRACT(MONTH FROM TBL_TESTE.TST_NASCIMENTO) = 2
	AND
	EXTRACT(DAY FROM TBL_TESTE.TST_NASCIMENTO) >= 29
	AND
	MOD(EXTRACT(YEAR FROM TBL_TESTE.TST_NASCIMENTO), 4) = 0
	THEN
	EXTRACT (DAY FROM CURRENT_DATE) - EXTRACT(DAY FROM TBL_TESTE.TST_NASCIMENTO) || ' dias ' ||
	EXTRACT (MONTH FROM CURRENT_DATE) - EXTRACT(MONTH FROM TBL_TESTE.TST_NASCIMENTO) + 1 || ' meses ' ||
	EXTRACT (YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM TBL_TESTE.TST_NASCIMENTO) || ' anos.'
	
	WHEN
	EXTRACT (DAY FROM CURRENT_DATE) - EXTRACT(DAY FROM TBL_TESTE.TST_NASCIMENTO) < 0
	AND
	EXTRACT (MONTH FROM CURRENT_DATE) - EXTRACT(MONTH FROM TBL_TESTE.TST_NASCIMENTO) < 0
	THEN
	(EXTRACT (DAY FROM CURRENT_DATE) - EXTRACT(DAY FROM TBL_TESTE.TST_NASCIMENTO)) * (-1)
	|| ' dias ' ||
	(EXTRACT (MONTH FROM CURRENT_DATE) - EXTRACT(MONTH FROM TBL_TESTE.TST_NASCIMENTO)) * (-1) ||
	' meses ' ||
	EXTRACT (YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM TBL_TESTE.TST_NASCIMENTO) ||
	' anos. '
	
	WHEN
	EXTRACT (DAY FROM CURRENT_DATE) - EXTRACT(DAY FROM TBL_TESTE.TST_NASCIMENTO) < 0
	THEN
	(EXTRACT (DAY FROM CURRENT_DATE) - EXTRACT(DAY FROM TBL_TESTE.TST_NASCIMENTO)) * (-1)
	|| ' dias ' ||
	(EXTRACT (MONTH FROM CURRENT_DATE) - EXTRACT(MONTH FROM TBL_TESTE.TST_NASCIMENTO)) ||
	' meses ' ||
	EXTRACT (YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM TBL_TESTE.TST_NASCIMENTO) ||
	' anos. '
	
	WHEN
	EXTRACT (MONTH FROM CURRENT_DATE) - EXTRACT(MONTH FROM TBL_TESTE.TST_NASCIMENTO) < 0
	THEN
	(EXTRACT (DAY FROM CURRENT_DATE) - EXTRACT(DAY FROM TBL_TESTE.TST_NASCIMENTO))
	|| ' dias ' ||
	(EXTRACT (MONTH FROM CURRENT_DATE) - EXTRACT(MONTH FROM TBL_TESTE.TST_NASCIMENTO)) * (-1) ||
	' meses ' ||
	EXTRACT (YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM TBL_TESTE.TST_NASCIMENTO) ||
	' anos. '
	
	ELSE
	EXTRACT (DAY FROM CURRENT_DATE) - EXTRACT(DAY FROM TBL_TESTE.TST_NASCIMENTO)
	|| ' dias ' ||
	EXTRACT (MONTH FROM CURRENT_DATE) - EXTRACT(MONTH FROM TBL_TESTE.TST_NASCIMENTO) ||
	' meses ' ||
	EXTRACT (YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM TBL_TESTE.TST_NASCIMENTO) ||
	' anos. '
	
END FROM TBL_TESTE;
