#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from ./src/yacc.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "./src/yacc.y"

int yylex(void);
void yyerror(char* s);

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <limits.h>
#define TAMANHO_IDENTIFICADOR 7
#define CHAR_ERRO "N/A"

typedef struct node {
    char tipo_variavel[TAMANHO_IDENTIFICADOR];
    char* nome_variavel;
    int valor_inteiro;
    char* valor_string;
    struct node* ptr_proximo_no;
} node_t;

typedef struct lista {
    node_t* ptr_primeiro_lista;
    struct lista* ptr_proxima_lista;
} lista_t;

typedef struct escopo {
    lista_t* ptr_topo;
} escopo_t;

// COMANDOS DA LISTA
void inserir_inteiro(char*, char*, int);
void inserir_string(char*, char*, char*);
lista_t* criar_lista();
void deletar_lista(lista_t*);

// COMANDOS DA PILHA
int vazia(escopo_t*);
escopo_t* criar_pilha();
void deletar_pilha(escopo_t*);
void push(lista_t*);
lista_t* pop();

// REGRAS DE NEGOCIO
lista_t* retornar_escopo(escopo_t*, char*);
int variavel_no_escopo_atual(lista_t*, char*);
void imprimir_variavel(char*);
void atualizar_variavel_numero(lista_t*, char*, int);
void atualizar_variavel_cadeia(lista_t*, char*, char*);
int retornar_valor_inteiro_de_variavel(escopo_t*, char*);
char* retornar_valor_string_de_variavel(escopo_t*, char*);
char* concatenar(const char*, const char*);
char* retornar_tipo_da_variavel(escopo_t*, char*);

// VARIAVEIS QUE SALVARAO A LISTA_ATUAL E A PILHA_ATUAL
lista_t* lista_atual = NULL;
escopo_t* escopo_atual = NULL;

#line 60 "./src/yacc.y"
typedef union {
    int numero;
    char* cadeia;
    char* identificador;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	INTEIRO	258
#define	IDENTIFICADOR	259
#define	BLOCO	260
#define	STRING	261
#define	TIPONUM	262
#define	TIPOCAD	263
#define	PRINT	264
#define	NOVO	265
#define	FIM	266
#define	IGUAL	267
#define	SOMA	268
#define	MULTIPLICACAO	269
#define	ABRPAREN	270
#define	FECPAREN	271
#define	MENOS	272
#define	TERMINADOR	273


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int INTEIRO;
static const int IDENTIFICADOR;
static const int BLOCO;
static const int STRING;
static const int TIPONUM;
static const int TIPOCAD;
static const int PRINT;
static const int NOVO;
static const int FIM;
static const int IGUAL;
static const int SOMA;
static const int MULTIPLICACAO;
static const int ABRPAREN;
static const int FECPAREN;
static const int MENOS;
static const int TERMINADOR;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,INTEIRO=258
	,IDENTIFICADOR=259
	,BLOCO=260
	,STRING=261
	,TIPONUM=262
	,TIPOCAD=263
	,PRINT=264
	,NOVO=265
	,FIM=266
	,IGUAL=267
	,SOMA=268
	,MULTIPLICACAO=269
	,ABRPAREN=270
	,FECPAREN=271
	,MENOS=272
	,TERMINADOR=273


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::INTEIRO=258;
const int YY_parse_CLASS::IDENTIFICADOR=259;
const int YY_parse_CLASS::BLOCO=260;
const int YY_parse_CLASS::STRING=261;
const int YY_parse_CLASS::TIPONUM=262;
const int YY_parse_CLASS::TIPOCAD=263;
const int YY_parse_CLASS::PRINT=264;
const int YY_parse_CLASS::NOVO=265;
const int YY_parse_CLASS::FIM=266;
const int YY_parse_CLASS::IGUAL=267;
const int YY_parse_CLASS::SOMA=268;
const int YY_parse_CLASS::MULTIPLICACAO=269;
const int YY_parse_CLASS::ABRPAREN=270;
const int YY_parse_CLASS::FECPAREN=271;
const int YY_parse_CLASS::MENOS=272;
const int YY_parse_CLASS::TERMINADOR=273;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		92
#define	YYFLAG		-32768
#define	YYNTBASE	19

#define YYTRANSLATE(x) ((unsigned)(x) <= 273 ? yytranslate[x] : 26)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     5,     9,    13,    16,    19,    20,    24,    30,    36,
    40,    46,    52,    54,    56,    58,    60,    65,    70,    75,
    77,    79,    81,    83,    90,    97,   104,   111,   119,   127,
   135,   143,   150,   157,   164,   171,   179,   187,   195,   203,
   210,   218,   225
};

static const short yyrhs[] = {    19,
     9,     4,    18,     0,    19,    10,     5,     0,    19,    11,
     5,     0,    19,    20,     0,    19,    21,     0,     0,     7,
     4,    18,     0,     7,     4,    12,     3,    18,     0,     7,
     4,    12,     4,    18,     0,     8,     4,    18,     0,     8,
     4,    12,     6,    18,     0,     8,     4,    12,     4,    18,
     0,    22,     0,    23,     0,    24,     0,    25,     0,     4,
    12,     3,    18,     0,     4,    12,     6,    18,     0,     4,
    12,     4,    18,     0,    22,     0,    23,     0,    24,     0,
    25,     0,     4,    12,     3,    13,     3,    18,     0,     4,
    12,     3,    13,     4,    18,     0,     4,    12,     4,    13,
     3,    18,     0,     4,    12,     4,    13,     4,    18,     0,
     7,     4,    12,     3,    13,     3,    18,     0,     7,     4,
    12,     3,    13,     4,    18,     0,     7,     4,    12,     4,
    13,     3,    18,     0,     7,     4,    12,     4,    13,     4,
    18,     0,     4,    12,     3,    17,     3,    18,     0,     4,
    12,     3,    17,     4,    18,     0,     4,    12,     4,    17,
     3,    18,     0,     4,    12,     4,    17,     4,    18,     0,
     7,     4,    12,     3,    17,     3,    18,     0,     7,     4,
    12,     3,    17,     4,    18,     0,     7,     4,    12,     4,
    17,     3,    18,     0,     7,     4,    12,     4,    17,     4,
    18,     0,     4,    12,     3,    14,     3,    18,     0,     7,
     4,    12,     3,    14,     3,    18,     0,     4,    12,     6,
    13,     6,    18,     0,     8,     4,    12,     6,    13,     6,
    18,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    67,    69,    73,    81,    82,    84,    87,    95,   104,   116,
   125,   134,   146,   147,   148,   149,   153,   155,   158,   177,
   178,   179,   180,   184,   186,   194,   202,   211,   220,   232,
   244,   260,   262,   270,   278,   287,   296,   308,   320,   336,
   341,   353,   363
};

static const char * const yytname[] = {   "$","error","$illegal.","INTEIRO",
"IDENTIFICADOR","BLOCO","STRING","TIPONUM","TIPOCAD","PRINT","NOVO","FIM","IGUAL",
"SOMA","MULTIPLICACAO","ABRPAREN","FECPAREN","MENOS","TERMINADOR","comandos",
"criacao","atribuicao","soma","subtracao","multiplicacao","concatenar",""
};
#endif

static const short yyr1[] = {     0,
    19,    19,    19,    19,    19,    19,    20,    20,    20,    20,
    20,    20,    20,    20,    20,    20,    21,    21,    21,    21,
    21,    21,    21,    22,    22,    22,    22,    22,    22,    22,
    22,    23,    23,    23,    23,    23,    23,    23,    23,    24,
    24,    25,    25
};

static const short yyr2[] = {     0,
     4,     3,     3,     2,     2,     0,     3,     5,     5,     3,
     5,     5,     1,     1,     1,     1,     4,     4,     4,     1,
     1,     1,     1,     6,     6,     6,     6,     7,     7,     7,
     7,     6,     6,     6,     6,     7,     7,     7,     7,     6,
     7,     6,     7
};

static const short yydefact[] = {     6,
     0,     0,     0,     0,     0,     0,     0,     4,     5,    13,
    14,    15,    16,     0,     0,     0,     0,     2,     3,     0,
     0,     0,     0,     7,     0,    10,     1,     0,     0,     0,
    17,     0,     0,    19,     0,    18,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     8,     0,     0,     9,    12,     0,    11,
    24,    25,    40,    32,    33,    26,    27,    34,    35,    42,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    28,    29,    41,    36,    37,    30,    31,    38,    39,    43,
     0,     0
};

static const short yydefgoto[] = {     1,
     8,     9,    10,    11,    12,    13
};

static const short yypact[] = {-32768,
     0,   -11,    10,    14,    21,    28,    55,-32768,-32768,-32768,
-32768,-32768,-32768,    -1,    -6,     1,    -3,-32768,-32768,     3,
    11,    18,    38,-32768,    34,-32768,-32768,    40,    36,    42,
-32768,    44,    46,-32768,    53,-32768,     9,    17,    43,    19,
    45,    47,    49,    51,    56,    57,    58,    59,    60,    61,
    48,    63,    50,-32768,    52,    54,-32768,-32768,    62,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
    64,    65,    66,    67,    68,    69,    70,    71,    72,    73,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
    80,-32768
};

static const short yypgoto[] = {-32768,
-32768,-32768,-32768,-32768,-32768,-32768
};


#define	YYLAST		91


static const short yytable[] = {    91,
    14,    20,    21,     2,    22,    23,     3,     4,     5,     6,
     7,    24,    25,    15,    27,    28,    29,    16,    26,    30,
    31,    51,    52,    32,    17,    53,    54,    33,    34,    55,
    35,    59,    18,    56,    57,    36,    60,    39,    43,    40,
    37,    38,    41,    42,    44,    45,    46,    47,    48,    49,
    71,    72,    74,    75,    76,    77,    78,    79,    50,    19,
    58,     0,    61,     0,    62,    73,    63,    80,    64,     0,
     0,     0,     0,    65,    66,    67,    68,    69,    70,    92,
     0,    81,    82,    83,    84,    85,    86,    87,    88,    89,
    90
};

static const short yycheck[] = {     0,
    12,     3,     4,     4,     6,    12,     7,     8,     9,    10,
    11,    18,    12,     4,    18,    13,    14,     4,    18,    17,
    18,    13,    14,    13,     4,    17,    18,    17,    18,    13,
    13,    13,     5,    17,    18,    18,    18,     4,     3,     6,
     3,     4,     3,     4,     3,     4,     3,     4,     3,     4,
     3,     4,     3,     4,     3,     4,     3,     4,     6,     5,
    18,    -1,    18,    -1,    18,     3,    18,     6,    18,    -1,
    -1,    -1,    -1,    18,    18,    18,    18,    18,    18,     0,
    -1,    18,    18,    18,    18,    18,    18,    18,    18,    18,
    18
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 67 "./src/yacc.y"
{
        imprimir_variavel(yyvsp[-1].identificador);
    ;
    break;}
case 2:
#line 70 "./src/yacc.y"
{
        push(lista_atual);
        lista_atual = criar_lista();
    ;
    break;}
case 3:
#line 74 "./src/yacc.y"
{ 
        lista_atual = pop();

        // SE O PROGRAMA ESTIVER PRESTES A ENCERRAR, MATAR A PILHA
        if(vazia(escopo_atual)) {
            deletar_pilha(escopo_atual);
        }
    ;
    break;}
case 7:
#line 87 "./src/yacc.y"
{
        if(vazia(escopo_atual)) {
            printf("Erro. Nao ha nenhum bloco aberto.\n");
        } else if(variavel_no_escopo_atual(lista_atual, yyvsp[-1].identificador)) {
            printf("Erro. Variavel ja foi declarada.\n");
        } else {
            inserir_inteiro("NUMERO", yyvsp[-1].identificador, 0);
        }
    ;
    break;}
case 8:
#line 96 "./src/yacc.y"
{
        if(vazia(escopo_atual)) {
            printf("Erro. Nao ha nenhum bloco aberto.\n");
        } else if(variavel_no_escopo_atual(lista_atual, yyvsp[-3].identificador)) {
            printf("Erro. Variavel ja foi declarada.\n");
        } else {
            inserir_inteiro("NUMERO", yyvsp[-3].identificador, yyvsp[-1].numero);
        }
    ;
    break;}
case 9:
#line 105 "./src/yacc.y"
{
        int valor = retornar_valor_inteiro_de_variavel(escopo_atual, yyvsp[-1].identificador);
        
        // SO IRA ATUALIZAR SE NAO HOUVER ERRO NENHUM
        if(valor != INT_MIN) {
            if(variavel_no_escopo_atual(lista_atual, yyvsp[-3].identificador)) {
                printf("Erro. Variavel ja foi declarada.\n");
            } else {
                inserir_inteiro("NUMERO", yyvsp[-3].identificador, valor);
            }
        }
    ;
    break;}
case 10:
#line 117 "./src/yacc.y"
{
        if(vazia(escopo_atual)) {
            printf("Erro. Nao ha nenhum bloco aberto.\n");
        } else if(variavel_no_escopo_atual(lista_atual, yyvsp[-1].identificador)) {
            printf("Erro. Variavel ja foi declarada.\n");
        } else {
            inserir_string("CADEIA", yyvsp[-1].identificador, "");
        }
    ;
    break;}
case 11:
#line 126 "./src/yacc.y"
{
        if(vazia(escopo_atual)) {
            printf("Erro. Nao ha nenhum bloco aberto.\n");
        } else if(variavel_no_escopo_atual(lista_atual, yyvsp[-3].identificador)) {
            printf("Erro. Variavel ja foi declarada.\n");
        } else {
            inserir_string("CADEIA", yyvsp[-3].identificador, yyvsp[-1].cadeia);
        }
    ;
    break;}
case 12:
#line 135 "./src/yacc.y"
{
        char* valor = strdup(retornar_valor_string_de_variavel(escopo_atual, yyvsp[-1].identificador));

        // SO IRA ATUALIZAR SE NAO HOUVER ERRO NENHUM
        if(!strcmp(valor, CHAR_ERRO)) {
            if(variavel_no_escopo_atual(lista_atual, yyvsp[-3].identificador)) {
                printf("Erro. Variavel ja foi declarada.\n");
            } else {
                inserir_string("CADEIA", yyvsp[-3].identificador, valor);
            }
        }
    ;
    break;}
case 17:
#line 153 "./src/yacc.y"
{
        atualizar_variavel_numero(lista_atual, yyvsp[-3].identificador, yyvsp[-1].numero);
    ;
    break;}
case 18:
#line 156 "./src/yacc.y"
{
        atualizar_variavel_cadeia(lista_atual, yyvsp[-3].identificador, yyvsp[-1].cadeia);
    ;
    break;}
case 19:
#line 159 "./src/yacc.y"
{
        char* tipo_variavel = strdup(retornar_tipo_da_variavel(escopo_atual, yyvsp[-1].identificador));
        char* valor_cadeia;
        int valor_numero;

        if(!strcmp(tipo_variavel, "NUMERO")) {
            valor_numero = retornar_valor_inteiro_de_variavel(escopo_atual, yyvsp[-1].identificador);

            if (valor_numero != INT_MIN) {
                atualizar_variavel_numero(lista_atual, yyvsp[-3].identificador, valor_numero);
            }
        } else {
            valor_cadeia = strdup(retornar_valor_string_de_variavel(escopo_atual, yyvsp[-1].identificador));

            if(strcmp(valor_cadeia, CHAR_ERRO)) {
                atualizar_variavel_cadeia(lista_atual, yyvsp[-3].identificador, valor_cadeia);
            }
        }
    ;
    break;}
case 24:
#line 184 "./src/yacc.y"
{
        atualizar_variavel_numero(lista_atual, yyvsp[-5].identificador, (yyvsp[-3].numero + yyvsp[-1].numero));
    ;
    break;}
case 25:
#line 187 "./src/yacc.y"
{
        int valor = retornar_valor_inteiro_de_variavel(escopo_atual, yyvsp[-1].identificador);
        
        // SO IRA ATUALIZAR SE NAO HOUVER ERRO NENHUM
        if(valor != INT_MIN) {
            atualizar_variavel_numero(lista_atual, yyvsp[-5].identificador, (yyvsp[-3].numero + valor));
        }
    ;
    break;}
case 26:
#line 195 "./src/yacc.y"
{
        int valor = retornar_valor_inteiro_de_variavel(escopo_atual, yyvsp[-3].identificador);
        
        // SO IRA ATUALIZAR SE NAO HOUVER ERRO NENHUM
        if(valor != INT_MIN) {
            atualizar_variavel_numero(lista_atual, yyvsp[-5].identificador, (yyvsp[-1].numero + valor));
        }
    ;
    break;}
case 27:
#line 203 "./src/yacc.y"
{
        int valor1 = retornar_valor_inteiro_de_variavel(escopo_atual, yyvsp[-3].identificador),
            valor2 = retornar_valor_inteiro_de_variavel(escopo_atual, yyvsp[-1].identificador);
        
        // SO IRA ATUALIZAR SE NAO HOUVER ERRO NENHUM
        if(valor1 != INT_MIN && valor2 != INT_MIN) {
            atualizar_variavel_numero(lista_atual, yyvsp[-5].identificador, (valor1 + valor2));
        }
    ;
    break;}
case 28:
#line 212 "./src/yacc.y"
{
        if(vazia(escopo_atual)) {
            printf("Erro. Nao ha nenhum bloco aberto.\n");
        } else if(variavel_no_escopo_atual(lista_atual, yyvsp[-5].identificador)) {
            printf("Erro. Variavel ja foi declarada.\n");
        } else {
            inserir_inteiro("NUMERO", yyvsp[-5].identificador, (yyvsp[-3].numero + yyvsp[-1].numero));
        }
    ;
    break;}
case 29:
#line 221 "./src/yacc.y"
{
        int valor = retornar_valor_inteiro_de_variavel(escopo_atual, yyvsp[-1].identificador);
        
        // SO IRA ATUALIZAR SE NAO HOUVER ERRO NENHUM
        if(valor != INT_MIN) {
            if(variavel_no_escopo_atual(lista_atual, yyvsp[-5].identificador)) {
                printf("Erro. Variavel ja foi declarada.\n");
            } else {
                inserir_inteiro("NUMERO", yyvsp[-5].identificador, (yyvsp[-3].numero + valor));
            }
        }
    ;
    break;}
case 30:
#line 233 "./src/yacc.y"
{
        int valor = retornar_valor_inteiro_de_variavel(escopo_atual, yyvsp[-3].identificador);
        
        // SO IRA ATUALIZAR SE NAO HOUVER ERRO NENHUM
        if(valor != INT_MIN) {
            if(variavel_no_escopo_atual(lista_atual, yyvsp[-5].identificador)) {
                printf("Erro. Variavel ja foi declarada.\n");
            } else {
                inserir_inteiro("NUMERO", yyvsp[-5].identificador, (yyvsp[-1].numero + valor));
            }
        }
    ;
    break;}
case 31:
#line 245 "./src/yacc.y"
{
        int valor1 = retornar_valor_inteiro_de_variavel(escopo_atual, yyvsp[-4].identificador),
            valor2 = retornar_valor_inteiro_de_variavel(escopo_atual, yyvsp[-2].identificador);

        // SO IRA ATUALIZAR SE NAO HOUVER ERRO NENHUM
        if(valor1 != INT_MIN && valor2 != INT_MIN) {
            if(variavel_no_escopo_atual(lista_atual, yyvsp[-5].identificador)) {
                printf("Erro. Variavel ja foi declarada.\n");
            } else {
                atualizar_variavel_numero(lista_atual, yyvsp[-5].identificador, (valor1 + valor2));
            }
        }
    ;
    break;}
case 32:
#line 260 "./src/yacc.y"
{
        atualizar_variavel_numero(lista_atual, yyvsp[-5].identificador, (yyvsp[-3].numero - yyvsp[-1].numero));
    ;
    break;}
case 33:
#line 263 "./src/yacc.y"
{
        int valor = retornar_valor_inteiro_de_variavel(escopo_atual, yyvsp[-1].identificador);
        
        // SO IRA ATUALIZAR SE NAO HOUVER ERRO NENHUM
        if(valor != INT_MIN) {
            atualizar_variavel_numero(lista_atual, yyvsp[-5].identificador, (yyvsp[-3].numero - valor));
        }
    ;
    break;}
case 34:
#line 271 "./src/yacc.y"
{
        int valor = retornar_valor_inteiro_de_variavel(escopo_atual, yyvsp[-3].identificador);
        
        // SO IRA ATUALIZAR SE NAO HOUVER ERRO NENHUM
        if(valor != INT_MIN) {
            atualizar_variavel_numero(lista_atual, yyvsp[-5].identificador, (yyvsp[-1].numero - valor));
        }
    ;
    break;}
case 35:
#line 279 "./src/yacc.y"
{
        int valor1 = retornar_valor_inteiro_de_variavel(escopo_atual, yyvsp[-3].identificador),
            valor2 = retornar_valor_inteiro_de_variavel(escopo_atual, yyvsp[-1].identificador);
        
        // SO IRA ATUALIZAR SE NAO HOUVER ERRO NENHUM
        if(valor1 != INT_MIN && valor2 != INT_MIN) {
            atualizar_variavel_numero(lista_atual, yyvsp[-5].identificador, (valor1 - valor2));
        }
    ;
    break;}
case 36:
#line 288 "./src/yacc.y"
{
        if(vazia(escopo_atual)) {
            printf("Erro. Nao ha nenhum bloco aberto.\n");
        } else if(variavel_no_escopo_atual(lista_atual, yyvsp[-5].identificador)) {
            printf("Erro. Variavel ja foi declarada.\n");
        } else {
            inserir_inteiro("NUMERO", yyvsp[-5].identificador, (yyvsp[-3].numero - yyvsp[-1].numero));
        }
    ;
    break;}
case 37:
#line 297 "./src/yacc.y"
{
        int valor = retornar_valor_inteiro_de_variavel(escopo_atual, yyvsp[-1].identificador);
        
        // SO IRA ATUALIZAR SE NAO HOUVER ERRO NENHUM
        if(valor != INT_MIN) {
            if(variavel_no_escopo_atual(lista_atual, yyvsp[-5].identificador)) {
                printf("Erro. Variavel ja foi declarada.\n");
            } else {
                inserir_inteiro("NUMERO", yyvsp[-5].identificador, (yyvsp[-3].numero - valor));
            }
        }
    ;
    break;}
case 38:
#line 309 "./src/yacc.y"
{
        int valor = retornar_valor_inteiro_de_variavel(escopo_atual, yyvsp[-3].identificador);
        
        // SO IRA ATUALIZAR SE NAO HOUVER ERRO NENHUM
        if(valor != INT_MIN) {
            if(variavel_no_escopo_atual(lista_atual, yyvsp[-5].identificador)) {
                printf("Erro. Variavel ja foi declarada.\n");
            } else {
                inserir_inteiro("NUMERO", yyvsp[-5].identificador, (yyvsp[-1].numero - valor));
            }
        }
    ;
    break;}
case 39:
#line 321 "./src/yacc.y"
{
        int valor1 = retornar_valor_inteiro_de_variavel(escopo_atual, yyvsp[-4].identificador),
            valor2 = retornar_valor_inteiro_de_variavel(escopo_atual, yyvsp[-2].identificador);

        // SO IRA ATUALIZAR SE NAO HOUVER ERRO NENHUM
        if(valor1 != INT_MIN && valor2 != INT_MIN) {
            if(variavel_no_escopo_atual(lista_atual, yyvsp[-5].identificador)) {
                printf("Erro. Variavel ja foi declarada.\n");
            } else {
                atualizar_variavel_numero(lista_atual, yyvsp[-5].identificador, (valor1 - valor2));
            }
        }
    ;
    break;}
case 40:
#line 336 "./src/yacc.y"
{
        int valor1 = yyvsp[-3].numero,
            valor2 = yyvsp[-1].numero;

        atualizar_variavel_cadeia(lista_atual, yyvsp[-5].identificador, (valor1 * valor2));
    ;
    break;}
case 41:
#line 342 "./src/yacc.y"
{
        if(vazia(escopo_atual)) {
            printf("Erro. Nao ha nenhum bloco aberto.\n");
        } else if(variavel_no_escopo_atual(lista_atual, yyvsp[-5].identificador)) {
            printf("Erro. Variavel ja foi declarada.\n");
        } else {
            inserir_inteiro("NUMERO", yyvsp[-5].identificador, (yyvsp[-3].numero * yyvsp[-1].numero));
        }
    ;
    break;}
case 42:
#line 353 "./src/yacc.y"
{
        char* concatenado = strdup(yyvsp[-3].cadeia, yyvsp[-1].cadeia);
        
        if(variavel_no_escopo_atual(lista_atual, yyvsp[-4].identificador)) {
            printf("Erro. Variavel ja foi declarada.\n");
        } else {
            atualizar_variavel_cadeia(lista_atual, yyvsp[-5].identificador, concatenado);
        }

        concatenado = NULL;
    ;
    break;}
case 43:
#line 364 "./src/yacc.y"
{
        char* concatenado = strdup(concatenar(yyvsp[-3].cadeia, yyvsp[-1].cadeia));

        if(vazia(escopo_atual)) {
            printf("Erro. Nao ha nenhum bloco aberto.\n");
        } else if(variavel_no_escopo_atual(lista_atual, yyvsp[-5].identificador)) {
            printf("Erro. Variavel ja foi declarada.\n");
        } else {
            inserir_string("CADEIA", yyvsp[-5].identificador, concatenado);
        }

        concatenado = NULL;
    ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 378 "./src/yacc.y"


extern FILE *yyin;

int main() {
    escopo_atual = criar_pilha();
    lista_atual = criar_lista();

	do {
		yyparse(); 
	} while(!feof(yyin));
}

void yyerror(char *s) {
   fprintf(stderr, "erro: %s\n", s);
}

void inserir_inteiro(char* tipo, char* lexema, int valor_inteiro) {
    // CRIANDO NOVO ELO PARA A LISTA
	node_t* ptr_novo_elo = (node_t*) malloc(sizeof(node_t));

    // SALVANDO OS VALORES NO ELO
    strcpy(ptr_novo_elo->tipo_variavel, tipo);
	ptr_novo_elo->nome_variavel = strdup(lexema);
	ptr_novo_elo->valor_inteiro = valor_inteiro;

    // ATUALIZANDO O PONTEIRO DE INICIO DA LISTA
	ptr_novo_elo->ptr_proximo_no = lista_atual->ptr_primeiro_lista;
    lista_atual->ptr_primeiro_lista = ptr_novo_elo;

	return;
}

void inserir_string(char* tipo, char* lexema, char* valor_string) {
    // CRIANDO NOVO ELO PARA A LISTA
	node_t* ptr_novo_elo = (node_t*) malloc(sizeof(node_t));

    // SALVANDO OS VALORES NO ELO
    strcpy(ptr_novo_elo->tipo_variavel, tipo);
	ptr_novo_elo->nome_variavel = strdup(lexema);
	ptr_novo_elo->valor_string = strdup(valor_string);

    // ATUALIZANDO O PONTEIRO DE INICIO DA LISTA
	ptr_novo_elo->ptr_proximo_no = lista_atual->ptr_primeiro_lista;

	return;
}

lista_t* criar_lista() {
    lista_t* nova_lista = (lista_t*) malloc(sizeof(lista_t));
    
    nova_lista->ptr_proxima_lista = NULL;
    nova_lista->ptr_primeiro_lista = NULL;
    
    return nova_lista;
}

void deletar_lista(lista_t* lista) {
    node_t* no = lista->ptr_primeiro_lista;

    // IRA PARAR QUANDO A LISTA ESTIVER VAZIA
    while(no != NULL) {
        // ATUALIZANDO O PONTEIRO DO INICIO DA LISTA
        lista->ptr_primeiro_lista = no->ptr_proximo_no;

        // LIBERANDO O NO DA MEMORIA
        free(no);

        // SALVANDO O PROXIMO NO NA VARIAVEL
        no = lista->ptr_primeiro_lista;
    }
    
    // LIMPANDO A LISTA DA MEMORIA
    free(lista);
    return;
}

int vazia(escopo_t* escopo){
    // VERIFICANDO SE A PILHA POSSUI ALGO EMPILHADO
    if(escopo->ptr_topo == NULL) {
        return 1;
    }

    return 0;
}

escopo_t* criar_pilha() {
    escopo_t* pilha = (escopo_t*) malloc(sizeof(escopo_t));
    
    pilha->ptr_topo = NULL;
    
    return pilha;
}

void deletar_pilha(escopo_t* pilha) {
    lista_t* lista = pilha->ptr_topo;

    // IRA PARAR QUANDO A PILHA ESTIVER VAZIA
    while(!vazia(pilha)) {
        // ATUALIZANDO O PONTEIRO DO TOPO DA PILHA
        pilha->ptr_topo = lista->ptr_proxima_lista;

        // DELETANDO A LISTA
        deletar_lista(lista);

        // ATUALIZANDO O PONTEIRO PARA OUTRA LISTA
        lista = pilha->ptr_topo;
    }
    
    // LIMPANDO A PILHA DA MEMORIA
    free(pilha);
    return;
}

void push(lista_t* lista_atual) {
    // INSERINDO UMA NOVA LISTA NO TOPO DA PILHA
    lista_atual->ptr_proxima_lista = escopo_atual->ptr_topo;   

    // ATUALIZANDO O PONTEIRO
    escopo_atual->ptr_topo = lista_atual;

    return;
}

lista_t* pop() {
    lista_t* temp = NULL;

    // VERIFICANDO SE A PILHA ESTA VAZIA
    if(vazia(escopo_atual)) {
        printf("Erro. Pilha vazia.\n");
        return NULL;
    }

    // SALVANDO A LISTA QUE ESTA NO TOPO DA PILHA
    temp = escopo_atual->ptr_topo;

    // REMOVENDO O TOPO DA PILHA E EXCLUINDO DA MEMORIA
    escopo_atual->ptr_topo = escopo_atual->ptr_topo->ptr_proxima_lista;
    free(temp);

    return temp;
}

lista_t* retornar_escopo(escopo_t* escopo, char* nome_variavel) {
    escopo_t* novo_escopo = (escopo_t*) malloc(sizeof(escopo_t));
    lista_t* nova_lista = NULL;

    novo_escopo->ptr_topo = escopo->ptr_topo->ptr_proxima_lista;

    // SE CHEGAR A BASE DA PILHA E NAO TIVER MAIS NADA
    if(novo_escopo->ptr_topo == NULL) {
        return NULL;
    }
    
    // VERIFICA SE NESTE ESCOPO TEM A VARIAVEL
    if(variavel_no_escopo_atual(novo_escopo->ptr_topo, nome_variavel)) {
        nova_lista = novo_escopo->ptr_topo;
    } else {
        nova_lista = retornar_escopo(novo_escopo, nome_variavel);
    }

    free(novo_escopo);
    return nova_lista;
}

int variavel_no_escopo_atual(lista_t* lista, char* nome_variavel) {
    node_t* no = lista->ptr_primeiro_lista;

    // LACO IRA PARA DE EXECUTAR SE no FOR NULO
    while(no != NULL) {
        // COMPARANDO AS STRINGS
        if(!strcmp(no->nome_variavel, nome_variavel)) {
            return 1; // SE EXISTIR, RETORNAR VERDADE
        }

        no = no->ptr_proximo_no;
    }

    // SE CHGOU ATE AQUI, ENTAO A VARIAVEL NAO EXISTE NO ESCOPO ATUAL
    return 0;
}

void imprimir_variavel(char* nome_variavel) {
    node_t* no = NULL;
    lista_t* temp = NULL;

    // VERIFICANDO SE no ESTA NO ESCOPO ATUAL
    if(variavel_no_escopo_atual(lista_atual, nome_variavel)) {
        no = lista_atual->ptr_primeiro_lista;
    } else { // SE NAO ESTIVER, PEGUE DA PILHA
        temp = retornar_escopo(escopo_atual, nome_variavel);
        
        // SO ATRIBUIR AO no SE REALEMNTE EXISTIR
        if(temp != NULL) {
            no = temp->ptr_primeiro_lista;
        }
    }

    // SE no NAO FOI ATUALIZANDO, REPORTAR ERRO E ABORTAR FUNCAO
    if(no == NULL) {
        printf("Erro: variavel não declarada.\n");
        return;
    }

    // ITERANDO PELA LISTA PARA PEGAR O no CORRETO
    while(no != NULL) {
        // VERIFICANDO SE AS VARIAVEIS BATEM
        if(!strcmp(no->nome_variavel, nome_variavel)) {
            // VERIFICANDO O TIPO PARA A IMPRESSAO
            if(!strcmp(no->tipo_variavel, "NUMERO")) {
                printf("%d\n", no->valor_inteiro);
            } else {
                printf("%s\n", no->valor_string);
            }
        }

        no = no->ptr_proximo_no;
    }
    
    return;
}

void atualizar_variavel_numero(lista_t* lista, char* nome_variavel, int novo_valor) {
    node_t* no = NULL;
    lista_t* temp = NULL;

    // VERIFICANDO SE no ESTA NO ESCOPO ATUAL
    if(variavel_no_escopo_atual(lista, nome_variavel)) {
        no = lista->ptr_primeiro_lista;
    } else { // SE NAO ESTIVER, PEGUE DA PILHA
        temp = retornar_escopo(escopo_atual, nome_variavel);
        no = temp->ptr_primeiro_lista;
        temp = NULL;
    }

    // SE no NAO FOI ATUALIZANDO, REPORTAR ERRO E ABORTAR FUNCAO
    if(no == NULL) {
        printf("Erro: variavel não declarada.\n");
        return;
    }

    // ITERANDO PELA LISTA PARA PEGAR O no CORRETO
    while(no != NULL) {
        if(!strcmp(no->nome_variavel, nome_variavel)) {
            no->valor_inteiro = novo_valor;
        }

        no = no->ptr_proximo_no;
    }

    return;
}

void atualizar_variavel_cadeia(lista_t* lista, char* nome_variavel, char* novo_valor) {
    node_t* no = NULL;
    lista_t* temp = NULL;

    // VERIFICANDO SE no ESTA NO ESCOPO ATUAL
    if(variavel_no_escopo_atual(lista, nome_variavel)) {
        no = lista->ptr_primeiro_lista;
    } else { // SE NAO ESTIVER, PEGUE DA PILHA
        temp = retornar_escopo(escopo_atual, nome_variavel);
        no = temp->ptr_primeiro_lista;
        temp = NULL;
    }

    // SE no NAO FOI ATUALIZANDO, REPORTAR ERRO E ABORTAR FUNCAO
    if(no == NULL) {
        printf("Erro: variavel não declarada.\n");
        return;
    }
    
    // ITERANDO PELA LISTA PARA PEGAR O no CORRETO
    while(no != NULL) {
        if(!strcmp(no->nome_variavel, nome_variavel)) {
            no->valor_string = strdup(novo_valor);
        }

        no = no->ptr_proximo_no;
    }

    return;
}

int retornar_valor_inteiro_de_variavel(escopo_t* escopo, char* nome_variavel) {
    node_t* no = NULL;
    lista_t* temp = escopo->ptr_topo;

    // VERIFICA SE VARIAVEL ESTA NO ESCOPO ATUAL
    if(variavel_no_escopo_atual(temp, nome_variavel)) {
        no = temp->ptr_primeiro_lista;
    } else { // SE NAO EXISTIR, BUSCAR NA PILHA
        temp = retornar_escopo(escopo, nome_variavel);

        // SO ATRIBUIR AO no SE REALEMNTE EXISTIR
        if(temp != NULL) {
            no = temp->ptr_primeiro_lista;
        }
    }

    // SE no NAO FOI ATUALIZANDO, REPORTAR ERRO E ABORTAR FUNCAO
    if(no == NULL) {
        printf("Erro: variavel nao existe.\n");
        return INT_MIN;
    }

    // ITERANDO PELA LISTA PARA PEGAR O no CORRETO
    while(no != NULL) {
        if(!strcmp(no->nome_variavel, nome_variavel)) {
            // IRA SALVAR SO E SOMENTE SE FOR DO TIPO NUMERO
            if(!strcmp(no->tipo_variavel, "NUMERO")) {
                return no->valor_inteiro;
            }
        }
    }

    // SE CHEGOU ATE AQUI, ENTAO HA ERRO
    printf("Erro: tipos incompativeis.\n");
    return INT_MIN;
}

char* retornar_valor_string_de_variavel(escopo_t* escopo, char* nome_variavel) {
    node_t* no = NULL;
    lista_t* temp = escopo->ptr_topo;

    // VERIFICA SE VARIAVEL ESTA NO ESCOPO ATUAL
    if(variavel_no_escopo_atual(temp, nome_variavel)) {
        no = temp->ptr_primeiro_lista;
    } else { // SE NAO EXISTIR, BUSCAR NA PILHA
        temp = retornar_escopo(escopo, nome_variavel);

        // SO ATRIBUIR AO no SE REALEMNTE EXISTIR
        if(temp != NULL) {
            no = temp->ptr_primeiro_lista;
        }
    }

    // SE no NAO FOI ATUALIZANDO, REPORTAR ERRO E ABORTAR FUNCAO
    if(no == NULL) {
        printf("Erro: variavel nao existe.\n");
        return CHAR_ERRO;
    }

    // ITERANDO PELA LISTA PARA PEGAR O no CORRETO
    while(no != NULL) {
        if(!strcmp(no->nome_variavel, nome_variavel)) {
            // IRA SALVAR SO E SOMENTE SE FOR DO TIPO NUMERO
            if(!strcmp(no->tipo_variavel, "CADEIA")) {
                return no->valor_string;
            }
        }
    }

    // SE CHEGOU ATE AQUI, ENTAO HA ERRO
    printf("Erro: tipos incompativeis.\n");
    return CHAR_ERRO;
}

char* concatenar(const char* const string1, const char* const string2) {
    char* resultado;
    char* aux;
    
    // COPIANDO PRIMEIRA PARTE DA STRING
    resultado = strdup(string1);
    resultado[strlen(resultado) - 1] = '\0';

    // COPIANDO SEGUNDA PARTE DA STRING
    strncpy(aux, string2 + 1, strlen(string2) - 1);
    strcat(resultado, aux);

    // LIMPANDO aux DA MEMORIA
    aux == NULL;

    return resultado;
}

char* retornar_tipo_da_variavel(escopo_t* escopo, char* nome_variavel) {
    char* tipo;
    node_t* no = NULL;
    lista_t* temp = escopo->ptr_topo;

    // VERIFICA SE VARIAVEL ESTA NO ESCOPO ATUAL
    if(variavel_no_escopo_atual(temp, nome_variavel)) {
        no = temp->ptr_primeiro_lista;
    } else { // SE NAO EXISTIR, BUSCAR NA PILHA
        temp = retornar_escopo(escopo, nome_variavel);

        // SO ATRIBUIR AO no SE REALEMNTE EXISTIR
        if(temp != NULL) {
            no = temp->ptr_primeiro_lista;
        }
    }

    // SE no NAO FOI ATUALIZANDO, REPORTAR ERRO E ABORTAR FUNCAO
    if(no == NULL) {
        printf("Erro: variavel nao existe.\n");
        return CHAR_ERRO;
    }

    // ITERANDO PELA LISTA PARA PEGAR O no CORRETO
    while(no != NULL) {
        if(!strcmp(no->nome_variavel, nome_variavel)) {
            tipo = strdup(no->tipo_variavel);
            break;
        }
    }

    return tipo;
}
