BEGIN;
CREATE OR REPLACE FUNCTION TRANSFERENCIA(NUMERIC, INTEGER, INTEGER)
RETURNS BOOLEAN LANGUAGE PLPGSQL AS $$
DECLARE
	valor ALIAS FOR $1;
	contaTransfere ALIAS FOR $2;
	contaRecebe ALIAS FOR $3;
	RES BOOLEAN := FALSE;
BEGIN
	IF (SELECT CON_CREDITO FROM TBL_CONTA WHERE TBL_CONTA.CON_ID = contaTransfere) >= valor AND (SELECT CON_ID FROM TBL_CONTA WHERE TBL_CONTA.CON_ID = contaRecebe) IS NOT NULL THEN
		UPDATE TBL_CONTA SET CON_CREDITO = CON_CREDITO + valor WHERE CON_ID = contaRecebe;
		UPDATE TBL_CONTA SET CON_CREDITO = CON_CREDITO - valor WHERE CON_ID = contaTransfere;
		RES := TRUE;
	END IF;
RETURN RES;
END;
$$;
END;
