BEGIN;
	SELECT CON_PESSOA, CON_CREDITO FROM TBL_CONTA WHERE CON_ID = 1 AND CON_CREDITO >= 100.00;
	SELECT CON_PESSOA, CON_CREDITO FROM TBL_CONTA WHERE CON_ID = 3;
	UPDATE TBL_CONTA SET CON_CREDITO = CON_CREDITO + 100.00 WHERE CON_ID = 3;
	UPDATE TBL_CONTA SET CON_CREDITO = CON_CREDITO - 100.00 WHERE CON_ID = 1;
COMMIT;
